# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

mem = {0:0, 1:1} 
def fib(n):
	if n not in mem:
		mem[n] = fib(n-1) + fib(n-2)
	return mem[n]

i = 1
sum = 0
t = 0
while (t == 0):
	x = fib(i)
	if not x % 2:
		sum = sum + x
	if x >= 4000000:
		t = 1
	i = i + 1
print sum